### PR TITLE
Feature/support node selector

### PR DESCRIPTION
**Pull request by sesubash**
updated to support dom node reference as selector

### CODE REVIEW

**Comment by sesubash** [comment]
@nzambello  please check this PR.

**Comment by nzambello** [comment]
@sesubash Nice, thank you for your PR.
Could you document this in the README?

I'll check the code ASAP

**Comment by sesubash** [comment]
@nzambello  updated the Readme.

**Review by nzambello — APPROVED** [review]

**Comment by nzambello** [comment]
@sesubash thank you for your contribution!
Released in v1.5.0

**Comment by sesubash** [comment]
Thanks @nzambello. This is a great plugin, glad that I was able to contribute.

**Pull request merged**
