### PR TITLE
Add prettier as pre-commit hook

### LINKED ISSUE #17: Add prettier as pre-commit hook.
I like it when the code looks the same across the whole library, even if this is a tiny one. How about adding [prettier](https://github.com/prettier/prettier) as a default pre-commit hook?

This is easily achievable as described [in the prettier docs](https://github.com/prettier/prettier#pre-commit-hook).

### PR DESCRIPTION
**Pull request by jaydp17**
@pnicolli @nzambello as discussed here the PR

Fixes  #17

### CODE REVIEW

**Review by nzambello — COMMENTED** [review]
Ok @jaydp17, I'll try it before merging but I agree with your changes.
I suggest to read about this: https://prettier.io/docs/en/usage.html#eslint for prettier integration in eslint

**Comment by nzambello** [comment]
Approved and tested changes, @jaydp17 look on that eslint configuration and then we can merge this.

**Comment by jaydp17** [comment]
@nzambello check 7fa9f17
I hope that's what you were referring to

**Review by nzambello — APPROVED** [review]
Ok, exactly! Thank you @jaydp17

**Pull request merged**
